version: '3'

services:
  postgres:
      image: postgres:11
      volumes:
        - /var/lib/postgresql/data
      ports:
        - ${POSTGRES_PORT}:5432
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      networks:
        - mytheresa_backend_challenge_dev



networks:
  mytheresa_backend_challenge_dev:
    driver: bridge

